### ISSUE TITLE
Project load is faulty when using networkshares or different drives

### ISSUE THREAD

**Issue by bbuerger** [deejaygraham/ndifference#1]
Hi,
first thanks for the nice library/program looks really well structured.
Using the UI, I add two assemblies which are on the network.
e.g \\nameofpc\oldbuild\assembly.dll and \\nameofpc\newbuild\assembly.dll
I then save the project to my local disk and try to run it -> everything works.
I try to load the project and boom, it doesn't work because the assembly locations should be stored using relative paths (not working with network shares or with different drives)
What is the reason to use relative paths and not absolute paths?

**Comment by deejaygraham** [comment]
Thanks for the comment. Sorry I've not been making many changes to this recently. You are correct, it should not be doing relative paths if they aren't related. I have a fix which I will commit shortly.
