### ISSUE TITLE
README - Stale XUnit link

### ISSUE THREAD

**Issue by bzier** [deejaygraham/ndifference#3]
The "Thank you's" section at the bottom of the `README` contain a stale link to the XUnit codeplex page, which Google Chrome is reporting as unsafe. According to the [codeplex archive](https://archive.codeplex.com/?p=xunit), the project moved to https://github.com/xunit/xunit and their current home page URL is https://xunit.github.io/

**Comment by deejaygraham** [comment]
Cool, thank you. Will update now.
